name: Configure AWS Credentials and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Allow the workflow to request OIDC tokens
  contents: read   # Allow the workflow to access the repository contents

jobs:
  configure-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::658044103911:role/Githubkn
          role-session-name: github-actions-session
          aws-region: us-east-1

      # Add additional steps here to deploy or interact with AWS services
      - name: Example Deployment Step
        run: |
          # Your deployment commands here
          echo "Deploying application..."
